// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// term_color_mode_rcpp
Rcpp::CharacterVector term_color_mode_rcpp(bool dsr);
RcppExport SEXP _terminalgraphics_term_color_mode_rcpp(SEXP dsrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type dsr(dsrSEXP);
    rcpp_result_gen = Rcpp::wrap(term_color_mode_rcpp(dsr));
    return rcpp_result_gen;
END_RCPP
}
// query_sixel_support_rcpp
Rcpp::LogicalVector query_sixel_support_rcpp();
RcppExport SEXP _terminalgraphics_query_sixel_support_rcpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(query_sixel_support_rcpp());
    return rcpp_result_gen;
END_RCPP
}
// query_tgp_support_rcpp
Rcpp::CharacterVector query_tgp_support_rcpp();
RcppExport SEXP _terminalgraphics_query_tgp_support_rcpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(query_tgp_support_rcpp());
    return rcpp_result_gen;
END_RCPP
}
// screen_dim_cpp
Rcpp::IntegerVector screen_dim_cpp();
RcppExport SEXP _terminalgraphics_screen_dim_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(screen_dim_cpp());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_terminalgraphics_term_color_mode_rcpp", (DL_FUNC) &_terminalgraphics_term_color_mode_rcpp, 1},
    {"_terminalgraphics_query_sixel_support_rcpp", (DL_FUNC) &_terminalgraphics_query_sixel_support_rcpp, 0},
    {"_terminalgraphics_query_tgp_support_rcpp", (DL_FUNC) &_terminalgraphics_query_tgp_support_rcpp, 0},
    {"_terminalgraphics_screen_dim_cpp", (DL_FUNC) &_terminalgraphics_screen_dim_cpp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_terminalgraphics(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
